zs_youtube:
  :source: youtube
  :channel_id: UCuTj9ukcxpg4esbAaxUW6UA

thenobot_youtube:
  :source: youtube
  :channel_id: UCV_q6WWviow5obtVmPODovg

thenobot_vimeo:
  :source: vimeo
  :username: thenobot

thenobot_flickr:
  :source: flickr
  :user_id: "74677593@N00"
  :api_key: "2b78ee62a1027fb4e72ce9c1d935a0e8"

zs_instagram:
  :source: instagram
  :token: "1931944135.207e759.0b7c980dc03347ffb5ff81c5f5a776b6"

#thenobot_twitter:
#  :source: twitter
#  :user_id: 6142272

#thenobot_soundcloud:
#  :source: soundcloud
#  :user_id: thenobot
#  :api_key: apigee

#thenobot_strava:
#  :source: strava
#  :api_key: "9820bc2d12991a05b143238099d43400dce018e3"
